# Generated by Django 4.1.2 on 2024-06-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion_comuna', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id_pregunta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'preguntas_frecuentes',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('seq_tipproduct', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_tip_producto', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_tip_usuario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('estado_usuario', models.FloatField()),
                ('comuna_id_comuna', models.ForeignKey(db_column='comuna_id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.comuna')),
                ('tipo_usuario_id_tipo_usuario', models.ForeignKey(db_column='tipo_usuario_id_tipo_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_corta', models.CharField(max_length=100)),
                ('desc_larga', models.CharField(max_length=200)),
                ('precio_real', models.BigIntegerField()),
                ('precio_oferta', models.BigIntegerField(blank=True, null=True)),
                ('path_imagen', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_producto_seq_tipproduct', models.ForeignKey(db_column='tipo_producto_seq_tipproduct', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.tipoproducto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.CharField(max_length=10)),
                ('hora_pedido', models.CharField(max_length=6)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('estado_pedido_id_estado', models.ForeignKey(db_column='estado_pedido_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.estadopedido')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.usuario')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('seq_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pedido_id_pedido', models.ForeignKey(db_column='pedido_id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.pedido')),
                ('productos_id_producto', models.ForeignKey(db_column='productos_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pizzapp.productos')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'unique_together': {('pedido_id_pedido', 'seq_pedido')},
            },
        ),
    ]
